# Generated by Django 2.2.9 on 2022-10-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220930_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=3000, verbose_name='Текст поста'),
        ),
    ]
